# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: qgis/qgis

pipelines:
  default:
    - step:
        services:
          - docker
        caches:
          - docker
          - pip
        script: # Modify the commands below to build your repository.
          - python -m pip install -r requirements.txt
          - python -m pip install -r requirements_developer.txt
          #- python -m pip install pytest-cov
          - python -m pip install nose2
          - apt-get update
          - apt-get -y install xvfb
          - apt-get -y install git-lfs
          - apt-get install -y wget
          - apt-get install -y unzip
          - Xvfb :1 -screen 0 1024x768x16 &> xvfb.log  &
          - ps aux | grep X
          - DISPLAY=:1.0
          - export DISPLAY
          - mkdir test-reports
          - git lfs install
          - git lfs fetch
          - git lfs pull
          - git lfs checkout
          - wget https://bitbucket.org/jakimowb/qgispluginsupport/downloads/qgisresources.zip -O qgisresources.zip
          - unzip qgisresources.zip
          - mkdir test-results
          - python make/setuprepository.py
          #- python -m nose2 discover tests "test_*.py" > test-reports/test-report.txt
          - python -m nose2 -s enmapboxtesting test_crosshair
          - python -m nose2 -s enmapboxtesting test_cursorlocationsvalues
          - python -m nose2 -s enmapboxtesting test_datasources
          - python -m nose2 -s enmapboxtesting test_docksanddatasources
          - python -m nose2 -s enmapboxtesting test_enmapbox
          - python -m nose2 -s enmapboxtesting test_enmapboxplugin
          - python -m nose2 -s enmapboxtesting test_layerproperties
          - python -m nose2 -s enmapboxtesting test_mapcanvas
          - python -m nose2 -s enmapboxtesting test_mimedata
          - python -m nose2 -s enmapboxtesting test_options
          - python -m nose2 -s enmapboxtesting test_speclibs
          - python -m nose2 -s enmapboxtesting test_spectralprofilesources
          - python -m nose2 -s enmapboxtesting test_testdata_dependency
          - python -m nose2 -s enmapboxtesting test_testing
          - python -m nose2 -s enmapboxtesting test_utils

          #- python -m nose2 -s enmapboxtesting test_applications

