# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7
pipelines:
  branches:
    '{master, develop}':
    - step:
        name: prepare environment
        services:
          - docker
        caches:
          - docker
          - pip
        script: # Modify the commands below to build your repository.
          - apt-get update
          #- apt-get -y install python3.7
          #- which python3.7
          #- update-alternatives --install /usr/bin/python python3 /usr/bin/python3.6 1
          #- update-alternatives --install /usr/bin/python python3 /usr/bin/python3.7 3
          #- update-alternatives --config python3
          - python3.7 --version
          - python3 --version
          - python --version
    - step:
        image: qgis/qgis
        name: test python code
        services:
          - docker
        caches:
          - docker
          - pip
        script: # Modify the commands below to build your repository.
          - python3 --version
          - apt-get update
          - apt-get -y install python3.7
          - python3 --version
          - apt-get -y install xvfb
          - apt-get -y install git-lfs
          - apt-get install -y wget
          - apt-get install -y unzip
          - Xvfb :1 -screen 0 1024x768x16 &> xvfb.log  &
          - ps aux | grep X
          - DISPLAY=:1.0
          - export DISPLAY
          - mkdir test-reports
          - python3 -m pip install -r requirements.txt
          - python3 -m pip install -r requirements_developer.txt
          - git lfs install
          - git lfs fetch
          - git lfs pull
          - git lfs checkout
          - python3 scripts/setuprepository.py
          - wget https://bitbucket.org/jakimowb/qgispluginsupport/downloads/qgisresources.zip -O qgisresources.zip
          - unzip qgisresources.zip
          - /bin/bash scripts/runtests.sh