#!/usr/bin/env python
"""
This file is auto-generated.
Do not edit manually, as changes might get overwritten.
"""
__author__ = "auto-generated by make\make.py"
__date__ = "2017-02-17T11:08:59"

import sys, os

thisDir = os.path.dirname(__file__)
# File path attributes: