from distutils.version import LooseVersion

ENMAPBOXGEOALGORITHMS_VERSION = '0.5.0'
ENMAPBOXGEOALGORITHMS_VERSION_OBJ = LooseVersion(ENMAPBOXGEOALGORITHMS_VERSION)
__version__ = ENMAPBOXGEOALGORITHMS_VERSION
