language: generic
sudo: false
dist: trusty
os: linux

_base_envs:
  - &coverage COVERAGE='true' PARALLEL='false'
  - &no_coverage COVERAGE='false' PARALLEL='true'
  - &optimize PYTHONOPTIMIZE=2 XTRATESTARGS=--ignore=dask/diagnostics
  - &no_optimize XTRATESTARGS=
  - &imports TEST_IMPORTS='true'
  - &no_imports TEST_IMPORTS='false'

jobs:
  fast_finish: true
  include:
    - env:
      - PYTHON=2.7
      - NUMPY=1.12.1
      - PANDAS=0.19.2
      - *coverage
      - *no_optimize
      - *no_imports

    - env:
      - PYTHON=2.7
      - NUMPY=1.13.0
      - PANDAS=0.20.2
      - *no_coverage
      - *optimize
      - *no_imports

    - env:
      - PYTHON=3.4
      - NUMPY=1.10.4
      - PANDAS=0.19.1
      - *no_coverage
      - *optimize
      - *no_imports
      if: type != pull_request

    - env:
      - PYTHON=3.5
      - NUMPY=1.12.1
      - PANDAS=0.19.2
      - *no_coverage
      - *no_optimize
      - *no_imports

    - env: &py36_env
      - PYTHON=3.6
      - UPSTREAM_DEV=1  # Install nightly versions of NumPy and pandas
      - NUMPY=1.13.0    # these are overridden later
      - PANDAS=0.20.3
      - *no_coverage
      - *no_optimize
      - *imports

    - env: *py36_env
      if: type != pull_request
      os: osx

  allow_failures:
    - os: osx


install:
  - source continuous_integration/travis/install.sh

script:
  - source continuous_integration/travis/run_tests.sh
  - flake8 dask
  - if [[ $TEST_IMPORTS == 'true' ]]; then source continuous_integration/travis/test_imports.sh; fi

after_success:
  - source continuous_integration/travis/after_success.sh

notifications:
  email: false
