name: Continuous integration

on:
  push:
    branches:
      - master
      - release-**
  pull_request:
    branches:
      - '**'
  release:
    types: [published]

jobs:
  # Run unit tests
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # qgis_version: [release-3_16, release-3_22, latest]
        qgis_version: [latest]
    env:
      QGIS_TEST_VERSION: ${{ matrix.qgis_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Test on QGIS
        run: |
          ls -la .docker/
          chmod +x .docker/run_docker_tests.sh
          docker-compose -f .docker/docker-compose.gh.yml run qgis ./usr/src/.docker/run_docker_tests.sh
